pipeline {
agent any

tools {
jdk 'java8'
maven 'Maven3.3.9'
}
stages {
     stage('Git clone') {
       steps {
          git 'https://github.com/snehitha-reddy/Game.git'
             }
        }
		stage('Build and compile') {
		steps {
		sh'''
		mvn clean install -U -Dmaven.test.skip=true
		'''
		}
		}
    }
}

